[build]
    publish = "public"
    command = "yarn build"
[build.environment]
    NODE_VERSION = "16.17.0"
    YARN_VERSION = "1.22.19"
    YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
    package = "@netlify/plugin-gatsby"
